# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateuploaded', models.DateTimeField(auto_now_add=True)),
                ('authors', models.CharField(default='Unknown', max_length=300)),
                ('doi', models.CharField(default='Unknown', max_length=300)),
                ('datepublished', models.CharField(default='Unknown', max_length=300)),
                ('name', models.CharField(default='Unknown', max_length=300)),
            ],
        ),
    ]
