# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='summary',
            field=models.TextField(default='No Summary Found'),
        ),
    ]
